Repository gaureshpai/create-next-quick, pull requests merged in 2025-10, with the labels that each got.

#12 feat: Add support for additional package managers and improve command execution logging
  README.md
  index.js
  lib/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#15 feat: improve project creation and shadcn init
  README.md
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#19 feat: Enhance CI/CD and dynamic test generation
  .github/workflows/ci.yml
  .github/workflows/welcome.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  test/generate-tests.js
  test/generated-test-cases.js
  test/test-cases.js
  test/test.js
Labels: hacktoberfest

#27 [BUG] fix issue #25 - have workflow use correct token
  .github/workflows/ci.yml
  .github/workflows/welcome.yml
Labels: bug, hacktoberfest, hacktoberfest-accepted

#49 Add CI workflow with automated PR test comments
  .github/pull_request_template.md
  .github/scripts/parse-logs.js
  .github/workflows/ci.yml
  .github/workflows/post-test-results.yml
  .github/workflows/welcome.yml
  package-lock.json
  package.json
  test/generated-test-cases.js
  test/test.js
Labels: documentation, hacktoberfest, hacktoberfest-accepted
